"""GitHub bootstrap helpers for workflow setup."""

from __future__ import annotations

import json
import shlex
import shutil
import subprocess
from pathlib import Path
from typing import Any

from autopilot.core.config import AutopilotConfig
from autopilot.core.onboarding import ProjectToolingReport, detect_project_tooling
from autopilot.core.project_store import resolve_runtime_project_entry, update_project_entry, utcnow_iso
from autopilot.core.repo_registry import find_canonical_git_root, get_github_repo
from autopilot.core.shipping import ShippingError, get_current_branch, get_default_branch
from autopilot.core.verification_bootstrap import VERIFICATION_BOOTSTRAP_RELPATH

GITHUB_BOOTSTRAP_WORKFLOW_RELPATH = ".github/workflows/autopilot-bootstrap.yml"
GITHUB_BOOTSTRAP_MANAGED_HEADER = "# This file was generated by `autopilot github`."


class GitHubBootstrapError(RuntimeError):
    """Raised when GitHub bootstrap cannot proceed safely."""


def _normalize_path(project_path: Path | str) -> Path:
    return Path(project_path).expanduser().resolve()


def _run_gh(cwd: Path, args: list[str]) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            ["gh", *args],
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=60,
        )
    except (FileNotFoundError, NotADirectoryError, PermissionError, subprocess.TimeoutExpired) as exc:
        raise GitHubBootstrapError("GitHub CLI `gh` is unavailable or the repository path is inaccessible.") from exc


def _command_tool_name(command: str) -> str:
    try:
        parts = shlex.split(command)
    except ValueError:
        return ""
    return str(parts[0] if parts else "").strip()


def _read_verifier_artifact(project_path: Path) -> list[dict[str, Any]]:
    artifact_path = project_path / VERIFICATION_BOOTSTRAP_RELPATH
    if not artifact_path.exists():
        return []
    try:
        payload = json.loads(artifact_path.read_text())
    except Exception:
        return []
    checks = payload.get("checks")
    if not isinstance(checks, list):
        return []
    normalized: list[dict[str, Any]] = []
    for check in checks:
        if not isinstance(check, dict):
            continue
        command = str(check.get("command") or "").strip()
        if not command:
            continue
        normalized.append(
            {
                "name": str(check.get("name") or "check").strip() or "check",
                "command": command,
                "kind": str(check.get("kind") or "acceptance_check").strip() or "acceptance_check",
                "category": str(check.get("category") or "").strip(),
                "source": str(check.get("source") or "verifiers").strip() or "verifiers",
                "tool_name": _command_tool_name(command),
            }
        )
    return normalized


def _fallback_checks(tooling: ProjectToolingReport) -> list[dict[str, Any]]:
    checks: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for gate in tooling.gates:
        name = str(gate.get("name") or "check").strip() or "check"
        command = str(gate.get("cmd") or "").strip()
        if not command:
            continue
        key = (name, command)
        if key in seen:
            continue
        seen.add(key)
        checks.append(
            {
                "name": name,
                "command": command,
                "kind": "quality_gate",
                "category": name,
                "source": str(gate.get("source") or "tooling"),
                "tool_name": _command_tool_name(command),
            }
        )
    if tooling.git_present:
        command = "git diff --check -- ."
        checks.append(
            {
                "name": "patch_hygiene",
                "command": command,
                "kind": "acceptance_check",
                "category": "acceptance",
                "source": "git:patch_hygiene",
                "tool_name": "git",
            }
        )
    return checks


def _step(name: str, *, uses: str | None = None, run: str | None = None, with_: dict[str, str] | None = None) -> dict[str, Any]:
    payload: dict[str, Any] = {"name": name}
    if uses:
        payload["uses"] = uses
    if run:
        payload["run"] = run
    if with_:
        payload["with"] = dict(with_)
    return payload


def _setup_steps(project_path: Path, tooling: ProjectToolingReport) -> list[dict[str, Any]]:
    steps: list[dict[str, Any]] = [_step("Check out repository", uses="actions/checkout@v4")]
    stacks = set(tooling.stacks)

    if "python" in stacks:
        steps.append(
            _step(
                "Set up Python",
                uses="actions/setup-python@v5",
                with_={"python-version": "3.12", "cache": "pip"},
            )
        )
        install_lines = ["python -m pip install --upgrade pip"]
        if (project_path / "requirements.txt").exists():
            install_lines.append("pip install -r requirements.txt")
        if (project_path / "pyproject.toml").exists():
            install_lines.append("pip install -e . || pip install . || true")
        if len(install_lines) > 1:
            steps.append(_step("Install Python dependencies", run="\n".join(install_lines)))

    package_manager = str(tooling.package_manager or "").strip()
    if "node" in stacks and package_manager:
        if package_manager == "pnpm":
            steps.append(_step("Set up pnpm", uses="pnpm/action-setup@v4", with_={"version": "9"}))
            steps.append(
                _step(
                    "Set up Node.js",
                    uses="actions/setup-node@v4",
                    with_={"node-version": "22", "cache": "pnpm"},
                )
            )
            steps.append(_step("Install Node dependencies", run="pnpm install --frozen-lockfile"))
        elif package_manager == "yarn":
            steps.append(
                _step(
                    "Set up Node.js",
                    uses="actions/setup-node@v4",
                    with_={"node-version": "22", "cache": "yarn"},
                )
            )
            steps.append(_step("Install Node dependencies", run="yarn install --frozen-lockfile"))
        elif package_manager == "bun":
            steps.append(_step("Set up Bun", uses="oven-sh/setup-bun@v2"))
            steps.append(_step("Install Node dependencies", run="bun install --frozen-lockfile"))
        else:
            steps.append(
                _step(
                    "Set up Node.js",
                    uses="actions/setup-node@v4",
                    with_={"node-version": "22", "cache": "npm"},
                )
            )
            install_cmd = "npm ci" if (project_path / "package-lock.json").exists() else "npm install"
            steps.append(_step("Install Node dependencies", run=install_cmd))

    if "rust" in stacks:
        steps.append(_step("Set up Rust", uses="dtolnay/rust-toolchain@stable"))

    if "go" in stacks:
        setup_with = {"go-version-file": "go.mod"} if (project_path / "go.mod").exists() else {"go-version": "stable"}
        steps.append(_step("Set up Go", uses="actions/setup-go@v5", with_=setup_with))

    return steps


def create_workflow_file(project_path: Path, tooling: ProjectToolingReport, checks: list[dict[str, Any]]) -> str:
    """Render the managed GitHub Actions workflow for one repository."""

    lines = [
        GITHUB_BOOTSTRAP_MANAGED_HEADER,
        "name: Autopilot Checks",
        "",
        "on:",
        "  pull_request:",
        "  workflow_dispatch:",
        "",
        "permissions:",
        "  contents: read",
        "",
        "jobs:",
        "  autopilot-checks:",
        "    runs-on: ubuntu-latest",
        "",
        "    steps:",
    ]

    for step in _setup_steps(project_path, tooling):
        lines.append(f"      - name: {step['name']}")
        uses = str(step.get("uses") or "").strip()
        if uses:
            lines.append(f"        uses: {uses}")
        with_payload = dict(step.get("with") or {})
        if with_payload:
            lines.append("        with:")
            for key, value in with_payload.items():
                lines.append(f'          {key}: "{value}"')
        run = str(step.get("run") or "").strip()
        if run:
            lines.append("        run: |")
            for line in run.splitlines():
                lines.append(f"          {line}")

    for index, check in enumerate(checks, start=1):
        name = str(check.get("name") or "check").strip() or f"check-{index}"
        command = str(check.get("command") or "").strip()
        if not command:
            continue
        lines.append(f"      - name: Run {name}")
        lines.append("        run: |")
        for line in command.splitlines():
            lines.append(f"          {line}")

    return "\n".join(lines).rstrip() + "\n"


def setup_github_actions(
    project_path: Path,
    *,
    tooling: ProjectToolingReport,
    checks: list[dict[str, Any]],
    overwrite: bool = False,
) -> dict[str, Any]:
    """Install or update the managed GitHub Actions workflow file."""

    workflow_path = project_path / GITHUB_BOOTSTRAP_WORKFLOW_RELPATH
    workflow_path.parent.mkdir(parents=True, exist_ok=True)
    new_content = create_workflow_file(project_path, tooling, checks)
    existing_content = workflow_path.read_text() if workflow_path.exists() else ""
    managed_existing = existing_content.startswith(GITHUB_BOOTSTRAP_MANAGED_HEADER)
    if workflow_path.exists() and existing_content != new_content and not (overwrite or managed_existing):
        raise GitHubBootstrapError(
            f"Workflow file already exists at {workflow_path}. Re-run with --overwrite to replace it."
        )

    changed = existing_content != new_content
    if changed:
        workflow_path.write_text(new_content)
    return {
        "workflow_path": str(workflow_path),
        "workflow_relpath": GITHUB_BOOTSTRAP_WORKFLOW_RELPATH,
        "workflow_exists": workflow_path.exists(),
        "managed_existing": managed_existing,
        "changed": changed,
    }


def bootstrap_github_repo(
    config: AutopilotConfig,
    *,
    project_path: Path | str = ".",
    project_id: str | None = None,
    install_workflow: bool = True,
    overwrite: bool = False,
) -> dict[str, Any]:
    """Bootstrap GitHub workflow setup for one checkout."""

    normalized_path = _normalize_path(project_path)
    if not normalized_path.exists():
        raise GitHubBootstrapError(f"Directory not found: {normalized_path}")
    if not normalized_path.is_dir():
        raise GitHubBootstrapError(f"Not a directory: {normalized_path}")

    try:
        project = resolve_runtime_project_entry(
            config,
            project_path=normalized_path,
            project_id=project_id,
            include_archived=True,
        )
    except ValueError as exc:
        raise GitHubBootstrapError(str(exc)) from exc
    if project_id and project is None:
        raise GitHubBootstrapError("Project not found in the Autopilot registry for this checkout.")

    repo_root = find_canonical_git_root(normalized_path)
    if repo_root is None:
        raise GitHubBootstrapError("Path is not inside a git repository.")

    github_repo = str(get_github_repo(repo_root) or "").strip()
    if not github_repo:
        raise GitHubBootstrapError("Origin remote is not a GitHub repository. Bootstrap is fail-closed without GitHub repo identity.")
    if shutil.which("gh") is None:
        raise GitHubBootstrapError("GitHub CLI `gh` is required for `autopilot github`.")

    auth_result = _run_gh(repo_root, ["auth", "status", "-h", "github.com"])
    gh_authenticated = auth_result.returncode == 0
    if not gh_authenticated:
        detail = str(auth_result.stderr or auth_result.stdout or "").strip() or "Run `gh auth login` first."
        raise GitHubBootstrapError(f"GitHub CLI is not authenticated for github.com. {detail}")

    try:
        current_branch = get_current_branch(repo_root)
        default_branch = get_default_branch(repo_root)
    except ShippingError as exc:
        raise GitHubBootstrapError(str(exc)) from exc

    tooling = detect_project_tooling(repo_root)
    checks = _read_verifier_artifact(repo_root) or _fallback_checks(tooling)
    if not checks:
        raise GitHubBootstrapError(
            "No reproducible checks were discovered. Run `autopilot init-verifiers` or add build/test/lint commands first."
        )

    workflow_preview = {
        "workflow_path": str(repo_root / GITHUB_BOOTSTRAP_WORKFLOW_RELPATH),
        "workflow_relpath": GITHUB_BOOTSTRAP_WORKFLOW_RELPATH,
        "workflow_exists": (repo_root / GITHUB_BOOTSTRAP_WORKFLOW_RELPATH).exists(),
        "managed_existing": False,
        "changed": False,
    }
    if install_workflow:
        if current_branch == default_branch:
            raise GitHubBootstrapError(
                f"Refusing to install workflow from protected branch `{current_branch}`. Create or switch to a feature branch first."
            )
        workflow_preview = setup_github_actions(
            repo_root,
            tooling=tooling,
            checks=checks,
            overwrite=overwrite,
        )

    compare_url = ""
    if current_branch and default_branch and current_branch != default_branch:
        compare_url = f"https://github.com/{github_repo}/compare/{default_branch}...{current_branch}?expand=1"
    workflow_url = f"https://github.com/{github_repo}/actions/workflows/{Path(GITHUB_BOOTSTRAP_WORKFLOW_RELPATH).name}"

    if project is not None:
        project["github_bootstrap"] = {
            "workflow_relpath": GITHUB_BOOTSTRAP_WORKFLOW_RELPATH,
            "updated_at": utcnow_iso(),
            "github_repo": github_repo,
            "current_branch": current_branch,
            "default_branch": default_branch,
            "compare_url": compare_url,
            "workflow_exists": bool(workflow_preview.get("workflow_exists")),
            "workflow_changed": bool(workflow_preview.get("changed")),
            "gh_authenticated": gh_authenticated,
        }
        update_project_entry(config, project)

    return {
        "project_path": str(normalized_path),
        "project_id": str(project.get("id") or "") if project is not None else "",
        "project_registered": project is not None,
        "repo_root": str(repo_root),
        "github_repo": github_repo,
        "gh_authenticated": gh_authenticated,
        "current_branch": current_branch,
        "default_branch": default_branch,
        "compare_url": compare_url,
        "workflow_url": workflow_url,
        "install_workflow": install_workflow,
        "tooling": tooling.to_dict(),
        "checks": checks,
        "workflow": workflow_preview,
    }
