"use client";
import { ControlPlaneLayout } from "@/components/control-plane-layout";
import { ControlPlaneLoadingShell } from "@/components/control-plane-loading-shell";
import {
  asRecord,
  describeRunResult,
  eventFamily,
  formatJson,
  formatScopeList,
  formatTimestamp,
  outcomeProjectId,
  outcomeProjectName,
  outcomeRuntimeAgentId,
  outcomeStoryId,
  outcomeStoryTitle,
  toNullableNumber,
  toNumber,
  toStringArray,
  toStringValue,
} from "@/lib/control-plane-data";
import { buildRuntimeAgentSectionProps } from "@/lib/control-plane-runtime-agent-props";
import { buildSessionDrilldownSectionProps } from "@/lib/control-plane-session-drilldown-props";
import {
  agentTimelineEntryKey,
  agentTimelineRowDomId,
  resolveRunLinkFromContext,
  resolveSessionEventFromContext,
  sessionContextRowDomId,
  sessionEventKey,
} from "@/lib/control-plane-linking";
import {
  buildHeaderSectionProps,
  buildMainSectionsProps,
  buildWorkspaceSectionProps,
} from "@/lib/control-plane-section-props";
import {
  agentTimelinePriority,
  matchesEventFilter,
  matchesRunFilter,
  sessionLineagePriority,
  sessionLineageTraits,
} from "@/lib/control-plane-triage";
import {
  useControlPlaneActions,
} from "@/lib/use-control-plane-actions";
import { useControlPlaneAgentNavigation } from "@/lib/use-control-plane-agent-navigation";
import { useControlPlaneAgentPriorityQueues } from "@/lib/use-control-plane-agent-priority-queues";
import { useControlPlaneBootstrap } from "@/lib/use-control-plane-bootstrap";
import { useControlPlaneDataLoader } from "@/lib/use-control-plane-data-loader";
import { useControlPlaneLinkedSelection } from "@/lib/use-control-plane-linked-selection";
import { useControlPlaneOperatorPersistence } from "@/lib/use-control-plane-operator-persistence";
import { useControlPlaneQueueAdvance } from "@/lib/use-control-plane-queue-advance";
import { useControlPlaneQueueTargetNavigation } from "@/lib/use-control-plane-queue-target-navigation";
import { useControlPlaneRevealFlows } from "@/lib/use-control-plane-reveal-flows";
import { useControlPlaneRunSelection } from "@/lib/use-control-plane-run-selection";
import { useControlPlaneRuntimeAgentModel } from "@/lib/use-control-plane-runtime-agent-model";
import { useControlPlaneSessionLineageModel } from "@/lib/use-control-plane-session-lineage-model";
import { useControlPlaneSessionOverviewModel } from "@/lib/use-control-plane-session-overview-model";
import { useControlPlaneSessionLineageQueues } from "@/lib/use-control-plane-session-lineage-queues";
import { useControlPlaneTriageInbox } from "@/lib/use-control-plane-triage-inbox";
import { useControlPlaneViewState } from "@/lib/use-control-plane-view-state";

export default function ControlPlanePage() {
  const TRIAGE_INBOX_FEEDBACK_LIMIT = 5;
  const {
    health,
    setHealth,
    projects,
    setProjects,
    controlPasses,
    setControlPasses,
    controlSummary,
    setControlSummary,
    sessions,
    setSessions,
    sessionSummary,
    setSessionSummary,
    controlProfiles,
    setControlProfiles,
    selectedSessionId,
    setSelectedSessionId,
    selectedAgentId,
    setSelectedAgentId,
    selectedRunId,
    setSelectedRunId,
    selectedRunResultIndex,
    setSelectedRunResultIndex,
    selectedPassId,
    setSelectedPassId,
    selectedSession,
    setSelectedSession,
    selectedAgent,
    setSelectedAgent,
    agentLoading,
    setAgentLoading,
    runFilter,
    setRunFilter,
    eventFilter,
    setEventFilter,
    sessionLineageFilter,
    setSessionLineageFilter,
    agentActivityFilter,
    setAgentActivityFilter,
    agentActivitySearch,
    setAgentActivitySearch,
    agentTimelineFilter,
    setAgentTimelineFilter,
    agentTimelineSearch,
    setAgentTimelineSearch,
    selectedAgentTimelineKey,
    setSelectedAgentTimelineKey,
    pendingAgentTimelineTarget,
    setPendingAgentTimelineTarget,
    dismissedAgentTimelineKeys,
    setDismissedAgentTimelineKeys,
    snoozedAgentTimelineUntil,
    setSnoozedAgentTimelineUntil,
    pendingAgentPriorityAutoAdvance,
    setPendingAgentPriorityAutoAdvance,
    pendingLineageAutoAdvance,
    setPendingLineageAutoAdvance,
    dismissedLineageQueueKeys,
    setDismissedLineageQueueKeys,
    snoozedLineageQueueUntil,
    setSnoozedLineageQueueUntil,
    lineageQueueNow,
    setLineageQueueNow,
    pendingSessionRowDomId,
    setPendingSessionRowDomId,
    pendingAgentTimelineRowDomId,
    setPendingAgentTimelineRowDomId,
    selectedSessionApprovalId,
    setSelectedSessionApprovalId,
    selectedSessionIssueId,
    setSelectedSessionIssueId,
    selectedSessionEventKey,
    setSelectedSessionEventKey,
    selectedSessionContextKind,
    setSelectedSessionContextKind,
    selectedTriageInboxKey,
    setSelectedTriageInboxKey,
    sessionQueueAdvanceFeedback,
    setSessionQueueAdvanceFeedback,
    agentQueueAdvanceFeedback,
    setAgentQueueAdvanceFeedback,
    sessionQueueFocusDelta,
    setSessionQueueFocusDelta,
    agentQueueFocusDelta,
    setAgentQueueFocusDelta,
    triageInboxFeedbackHistory,
    setTriageInboxFeedbackHistory,
    triageInboxFeedbackFilter,
    setTriageInboxFeedbackFilter,
    expandedTriageInboxResultGroups,
    setExpandedTriageInboxResultGroups,
    expandedSessionLineageQueues,
    setExpandedSessionLineageQueues,
    expandedAgentPriorityQueues,
    setExpandedAgentPriorityQueues,
    historySearch,
    setHistorySearch,
    entitySearch,
    setEntitySearch,
    refreshing,
    setRefreshing,
    sessionLoading,
    setSessionLoading,
    busyActionKey,
    setBusyActionKey,
    notice,
    setNotice,
    errorMessage,
    setErrorMessage,
    selectedSessionLineageEntryRef,
    selectedAgentTimelineEntryRef,
    selectedTriageInboxKeyRef,
    sessionLineageFilterRef,
  } = useControlPlaneViewState();

  const { loadOverview, loadSessionDetail, loadAgentDetail } = useControlPlaneDataLoader({
    selectedSessionId,
    setHealth,
    setProjects,
    setControlPasses,
    setControlSummary,
    setSessions,
    setSessionSummary,
    setControlProfiles,
    setErrorMessage,
    setSelectedSession,
    setSelectedRunId,
    setSelectedPassId,
  });

  const {
    refresh,
    recordTriageInboxFeedback,
    applyRecommendation,
    approveApproval,
    rejectApproval,
    applyApproval,
    resolveIssue,
    runAgentSuggestedCommand,
    applyControlPlan,
  } = useControlPlaneActions({
    selectedSessionId,
    selectedAgentId,
    selectedAgent,
    setRefreshing,
    setBusyActionKey,
    setNotice,
    setErrorMessage,
    setSelectedRunId,
    setSelectedPassId,
    setSelectedAgent,
    setEntitySearch,
    setPendingLineageAutoAdvance,
    setPendingAgentPriorityAutoAdvance,
    setTriageInboxFeedbackHistory,
    selectedSessionLineageEntryRef,
    selectedAgentTimelineEntryRef,
    selectedTriageInboxKeyRef,
    sessionLineageFilterRef,
    loadOverview,
    loadSessionDetail,
    loadAgentDetail,
    toStringValue,
    triageInboxFeedbackLimit: TRIAGE_INBOX_FEEDBACK_LIMIT,
  });

  useControlPlaneOperatorPersistence({
    selectedSessionId,
    selectedAgentId,
    dismissedLineageQueueKeys,
    setDismissedLineageQueueKeys,
    snoozedLineageQueueUntil,
    setSnoozedLineageQueueUntil,
    lineageQueueNow,
    setLineageQueueNow,
    sessionQueueFocusDelta,
    setSessionQueueFocusDelta,
    dismissedAgentTimelineKeys,
    setDismissedAgentTimelineKeys,
    snoozedAgentTimelineUntil,
    setSnoozedAgentTimelineUntil,
    agentQueueFocusDelta,
    setAgentQueueFocusDelta,
  });

  const { focusRuntimeAgent } = useControlPlaneBootstrap({
    sessions,
    controlPasses,
    selectedSessionId,
    selectedAgentId,
    selectedRunId,
    selectedRunResultIndex,
    selectedSession,
    loadSessionDetail,
    loadAgentDetail,
    setSelectedSessionId,
    setSelectedAgentId,
    setSelectedRunId,
    setSelectedRunResultIndex,
    setSelectedPassId,
    setSelectedAgent,
    setSelectedSession,
    setSelectedSessionApprovalId,
    setSelectedSessionIssueId,
    setSelectedSessionEventKey,
    setSelectedSessionContextKind,
    setEntitySearch,
    setSessionQueueAdvanceFeedback,
    setSessionQueueFocusDelta,
    setPendingLineageAutoAdvance,
    setLineageQueueNow,
    setSessionLoading,
    setAgentLoading,
    setErrorMessage,
    setAgentActivityFilter,
    setAgentActivitySearch,
    setAgentTimelineFilter,
    setAgentTimelineSearch,
    setSelectedAgentTimelineKey,
    setAgentQueueAdvanceFeedback,
    setAgentQueueFocusDelta,
    setPendingAgentPriorityAutoAdvance,
  });

  const {
    visibleProjects,
    filteredControlPassHistory,
    recentControlPasses,
    filteredSessionHistory,
    recentSessions,
    sortedProfiles,
    selectedPass,
    linkedApprovals,
    linkedRuns,
    filteredRuns,
    linkedIssues,
    approvalById,
    issueById,
    linkedAgentIds,
    filteredApprovals,
    filteredIssues,
    selectedSessionApproval,
    selectedSessionIssue,
    selectedSessionEvent,
    visibleSessionApprovals,
    visibleSessionIssues,
    selectedRun,
    filteredEvents,
    visibleSessionEvents,
    selectedRunResult,
    selectedControl,
  } = useControlPlaneSessionOverviewModel({
    projects,
    controlPasses,
    controlProfiles,
    sessions,
    selectedSession,
    selectedPassId,
    selectedRunId,
    selectedRunResultIndex,
    selectedSessionApprovalId,
    selectedSessionIssueId,
    selectedSessionEventKey,
    historySearch,
    entitySearch,
    runFilter,
    eventFilter,
  });
  useControlPlaneRunSelection({
    filteredRuns,
    linkedRuns,
    selectedRunId,
    selectedRunResultIndex,
    setSelectedRunId,
    setSelectedRunResultIndex,
  });
  const {
    sessionLineageEntries,
    selectedSessionLineageEntry,
    filteredSessionLineageEntries,
    sessionLineagePriorityCounts,
    nextBestSessionLineageEntry,
    selectedSessionLineagePriority,
    visibleSessionLineageEntries,
    sessionLineageStatusCounts,
    sessionLineageDecisionCount,
    sessionLineageAttentionCount,
    sessionLineageEventCount,
    sessionLineageAgentCount,
    sessionLineageAgentLinkedCount,
    sessionLineageFilterCounts,
    latestAgentLinkedLineageEntry,
    attentionSessionLineageEntries,
    decisionSessionLineageEntries,
    attentionSessionLineageQueue,
    decisionSessionLineageQueue,
    attentionQueuePosition,
    decisionQueuePosition,
    nextAttentionSessionLineageEntry,
    nextDecisionSessionLineageEntry,
    currentSessionLineageQueue,
    hiddenAttentionQueueCount,
    hiddenDecisionQueueCount,
    persistedLineageQueueState,
    persistedDismissedLineageQueueCount,
    persistedSnoozedLineageQueueCount,
    hasPersistedLineageQueuePreferences,
    selectedSessionLineageTraits,
  } = useControlPlaneSessionLineageModel({
    approvalById,
    issueById,
    linkedRuns,
    selectedSession,
    selectedSessionId,
    selectedRunId,
    selectedRunResultIndex,
    sessionLineageFilter,
    dismissedLineageQueueKeys,
    snoozedLineageQueueUntil,
    lineageQueueNow,
    selectedSessionLineageEntryRef,
    sessionLineageFilterRef,
    setExpandedSessionLineageQueues,
  });
  const {
    syncLinkedSelection,
    inspectSessionLineageEntry,
    focusSessionLineageEntry,
    openSelectedRunResultInTimeline,
    selectedSessionContext,
    revealSelectedSessionContextRow,
    revealSelectedSessionContextInAgentTimeline,
  } = useControlPlaneLinkedSelection({
    linkedRuns,
    selectedSession,
    selectedSessionApproval,
    selectedSessionIssue,
    selectedSessionEvent,
    selectedSessionEventKey,
    selectedSessionContextKind,
    selectedRun,
    selectedRunResult,
    setSelectedSessionApprovalId,
    setSelectedSessionIssueId,
    setSelectedSessionEventKey,
    setSelectedSessionContextKind,
    setSelectedRunId,
    setSelectedRunResultIndex,
    setSelectedAgentId,
    setAgentTimelineFilter,
    setAgentTimelineSearch,
    setSelectedAgentTimelineKey,
    setPendingAgentTimelineTarget,
    setPendingSessionRowDomId,
    setEntitySearch,
    setEventFilter,
    setErrorMessage,
    setSessionLineageFilter,
  });
  const {
    advanceSessionLineageQueue,
    advanceSessionLineageQueueFromEntry,
    dismissSessionLineageQueueEntry,
    snoozeSessionLineageQueueEntry,
    restoreSessionLineageQueue,
    resetSessionLineageQueuePreferences,
    toggleSessionLineageQueueExpansion,
    expandAllSessionLineageQueues,
    collapseAllSessionLineageQueues,
    openCurrentSessionLineageQueue,
    exportSessionLineageQueuePreferences,
  } = useControlPlaneSessionLineageQueues({
    attentionSessionLineageEntries,
    decisionSessionLineageEntries,
    selectedSessionLineageEntry,
    sessionLineageFilter,
    currentSessionLineageQueue,
    selectedSessionId,
    persistedLineageQueueState,
    pendingLineageAutoAdvance,
    setDismissedLineageQueueKeys,
    setSnoozedLineageQueueUntil,
    setLineageQueueNow,
    setNotice,
    setErrorMessage,
    setExpandedSessionLineageQueues,
    setSessionQueueAdvanceFeedback,
    setPendingLineageAutoAdvance,
    setSessionLineageFilter,
    focusSessionLineageEntry,
  });
  const {
    agentScopedRuns,
    agentScopedOutcomes,
    filteredAgentScopedRuns,
    filteredAgentScopedOutcomes,
    agentTimelineEntries,
    activeAgentTimelineEntries,
    filteredAgentTimelineEntries,
    agentTimelineFilterCounts,
    selectedAgentTimelineEntry,
    visibleAgentTimelineEntries,
    latestAgentApprovalEntry,
    latestAgentIssueEntry,
    latestAgentEventEntry,
    hiddenAgentTimelineEntryCount,
    persistedDismissedAgentTimelineCount,
    persistedSnoozedAgentTimelineCount,
    hasPersistedAgentTimelinePreferences,
    selectedAgentTimelineRunLink,
    agentTimelinePriorityCounts,
    nextBestAgentTimelineEntry,
    selectedAgentTimelinePriority,
    currentAgentPriorityQueue,
    criticalAgentTimelineEntries,
    highAgentTimelineEntries,
    criticalAgentTimelineQueue,
    highAgentTimelineQueue,
    criticalAgentTimelinePosition,
    highAgentTimelinePosition,
    nextCriticalAgentTimelineEntry,
    nextHighAgentTimelineEntry,
    selectedAgentTimelineEntryKeyValue,
  } = useControlPlaneRuntimeAgentModel({
    selectedAgentId,
    selectedAgent,
    linkedRuns,
    agentActivityFilter,
    agentActivitySearch,
    agentTimelineFilter,
    agentTimelineSearch,
    dismissedAgentTimelineKeys,
    snoozedAgentTimelineUntil,
    lineageQueueNow,
    selectedAgentTimelineKey,
    setSelectedAgentTimelineKey,
    setExpandedAgentPriorityQueues,
    selectedAgentTimelineEntryRef,
  });
  const {
    focusAgentTimeline,
    inspectAgentTimelineEntry,
  } = useControlPlaneAgentNavigation({
    linkedRuns,
    selectedAgent,
    selectedAgentId,
    syncLinkedSelection,
    setAgentTimelineFilter,
    setAgentTimelineSearch,
    setSelectedAgentTimelineKey,
  });
  const {
    toggleAgentPriorityQueueExpansion,
    expandAllAgentPriorityQueues,
    collapseAllAgentPriorityQueues,
    openCurrentAgentPriorityQueue,
    dismissAgentTimelineEntry,
    snoozeAgentTimelineEntry,
    restoreAgentTimelineHidden,
    resetAgentTimelinePreferences,
    exportAgentTimelinePreferences,
    advanceAgentPriorityQueueFromEntry,
  } = useControlPlaneAgentPriorityQueues({
    selectedAgentId,
    selectedAgentTimelineEntryRef,
    filteredAgentTimelineEntries,
    criticalAgentTimelineEntries,
    highAgentTimelineEntries,
    currentAgentPriorityQueue,
    dismissedAgentTimelineKeys,
    snoozedAgentTimelineUntil,
    lineageQueueNow,
    pendingAgentPriorityAutoAdvance,
    setDismissedAgentTimelineKeys,
    setSnoozedAgentTimelineUntil,
    setLineageQueueNow,
    setNotice,
    setErrorMessage,
    setExpandedAgentPriorityQueues,
    setPendingAgentPriorityAutoAdvance,
    setAgentQueueAdvanceFeedback,
    inspectAgentTimelineEntry,
  });
  const {
    restoreAgentTimelineEntryVisibility,
    revealAgentTimelineEntry,
    findSessionLineageEntryInSession,
    revealSessionLineageEntryInTimeline,
    findAgentTimelineEntryInSession,
  } = useControlPlaneRevealFlows({
    selectedAgentId,
    selectedAgent,
    linkedRuns,
    syncLinkedSelection,
    agentTimelineEntries,
    visibleAgentTimelineEntries,
    pendingAgentTimelineTarget,
    setPendingAgentTimelineTarget,
    pendingSessionRowDomId,
    setPendingSessionRowDomId,
    pendingAgentTimelineRowDomId,
    setPendingAgentTimelineRowDomId,
    setDismissedAgentTimelineKeys,
    setSnoozedAgentTimelineUntil,
    setLineageQueueNow,
    setAgentTimelineFilter,
    setAgentTimelineSearch,
    setSelectedAgentTimelineKey,
    setEntitySearch,
    setSelectedRunId,
    setSelectedRunResultIndex,
    setNotice,
  });
  const { openSessionQueueAdvanceTarget, openAgentQueueAdvanceTarget } =
    useControlPlaneQueueTargetNavigation({
      focusSessionLineageEntry,
      restoreAgentTimelineEntryVisibility,
      revealAgentTimelineEntry,
      inspectAgentTimelineEntry,
    });
  const {
    sessionQueueAdvanceFocusSummary,
    agentQueueAdvanceFocusSummary,
    sessionQueueAdvanceNoticeActions,
    agentQueueAdvanceNoticeActions,
  } = useControlPlaneQueueAdvance({
    sessionLineageFilter,
    sessionLineageEntriesCount: sessionLineageEntries.length,
    filteredSessionLineageEntriesCount: filteredSessionLineageEntries.length,
    sessionLineageFilterCounts,
    focusSessionLineageEntry,
    setSessionLineageFilter,
    sessionQueueAdvanceFeedback,
    setSessionQueueFocusDelta,
    currentSessionLineageQueue,
    openCurrentSessionLineageQueue,
    openSessionQueueAdvanceTarget,
    agentTimelineFilter,
    activeAgentTimelineEntriesCount: activeAgentTimelineEntries.length,
    filteredAgentTimelineEntriesCount: filteredAgentTimelineEntries.length,
    agentTimelineFilterCounts,
    focusAgentTimeline,
    inspectAgentTimelineEntry,
    agentQueueAdvanceFeedback,
    setAgentQueueFocusDelta,
    currentAgentPriorityQueue,
    openCurrentAgentPriorityQueue,
    openAgentQueueAdvanceTarget,
  });
  const {
    triageInboxItems,
    triageInboxItemCount,
    selectedTriageInboxItem,
    triageInboxFeedbackCounts,
    triageInboxFeedback,
    recentTriageInboxFeedback,
    groupedRecentTriageInboxFeedback,
    currentTriageInboxFeedbackGroup,
    syncedTriageInboxItem,
    advanceTriageInboxCursor,
    inspectTriageInboxItem,
    openTriageInboxHistoryGroup,
    inspectAndAdvanceTriageInboxItem,
    snoozeTriageInboxItem,
    dismissTriageInboxItem,
    syncTriageInboxCursorToSelection,
    toggleTriageInboxResultGroup,
    expandAllTriageInboxResultGroups,
    collapseAllTriageInboxResultGroups,
    openCurrentTriageInboxResultGroup,
  } = useControlPlaneTriageInbox({
    nextAttentionSessionLineageEntry,
    attentionSessionLineageEntries,
    selectedSessionLineageEntry,
    focusSessionLineageEntry,
    snoozeSessionLineageQueueEntry,
    dismissSessionLineageQueueEntry,
    nextDecisionSessionLineageEntry,
    decisionSessionLineageEntries,
    nextCriticalAgentTimelineEntry,
    criticalAgentTimelineEntries,
    selectedAgentTimelineEntryKeyValue,
    inspectAgentTimelineEntry,
    snoozeAgentTimelineEntry,
    dismissAgentTimelineEntry,
    nextHighAgentTimelineEntry,
    highAgentTimelineEntries,
    selectedTriageInboxKey,
    setSelectedTriageInboxKey,
    triageInboxFeedbackHistory,
    setTriageInboxFeedbackHistory,
    triageInboxFeedbackFilter,
    setTriageInboxFeedbackFilter,
    setExpandedTriageInboxResultGroups,
    selectedTriageInboxKeyRef,
    selectedAgentId,
    selectedSessionId,
    recordTriageInboxFeedback,
    triageInboxFeedbackLimit: TRIAGE_INBOX_FEEDBACK_LIMIT,
  });
  const loading = !controlSummary || !sessionSummary;

  if (loading) {
    return <ControlPlaneLoadingShell health={health} visibleProjects={visibleProjects} />;
  }

  const workspaceSectionProps = buildWorkspaceSectionProps({
    hasSelectedSession: Boolean(selectedSession),
    recentControlPasses,
    totalControlPassCount: controlPasses.length,
    selectedPassId,
    formatTimestamp,
    toStringValue,
    toNumber,
    setSelectedPassId,
    setSelectedSessionId,
    selectedRun,
    selectedRunResult,
    selectedRunResultIndex,
    setSelectedRunResultIndex,
    formatScopeList,
    describeRunResult,
    toStringArray,
    asRecord,
    selectedSessionEvents: selectedSession?.events || [],
    formatJson,
    sessionEventKey,
    resolveSessionEventFromContext,
    outcomeProjectId,
    outcomeProjectName,
    outcomeStoryId,
    outcomeStoryTitle,
    outcomeRuntimeAgentId,
    onOpenSelectedRunResultInTimeline: openSelectedRunResultInTimeline,
    focusRuntimeAgent,
    setEntitySearch,
    setSelectedRunId,
    syncLinkedSelection,
    sessionLineageEntries,
    linkedRunsCount: linkedRuns.length,
    linkedApprovalsCount: linkedApprovals.length,
    linkedIssuesCount: linkedIssues.length,
    linkedAgentCount: linkedAgentIds.length,
    sessionLineageDecisionCount,
    sessionLineageEventCount,
    sessionLineageAgentCount,
    sessionLineageStatusCounts,
    filteredSessionLineageEntriesCount: filteredSessionLineageEntries.length,
    sessionLineageFilter: sessionLineageFilter as
      | "all"
      | "attention"
      | "decisions"
      | "agent-linked",
    setSessionLineageFilter: (value) => {
      setSessionLineageFilter(value);
    },
    sessionLineageAttentionCount,
    sessionLineageAgentLinkedCount,
    persistedDismissedLineageQueueCount,
    persistedSnoozedLineageQueueCount,
    sessionLineagePriorityCounts,
    hasPersistedLineageQueuePreferences,
    exportSessionLineageQueuePreferences,
    resetSessionLineageQueuePreferences,
    selectedSessionLineageEntry,
    selectedSessionLineagePriority,
    selectedSessionLineageTraits,
    nextBestSessionLineageEntry,
    attentionSessionLineageEntries,
    decisionSessionLineageEntries,
    latestAgentLinkedLineageEntry,
    inspectSessionLineageEntry,
    advanceSessionLineageQueue,
    focusSessionLineageEntry,
    expandedSessionLineageQueues,
    currentSessionLineageQueue,
    expandAllSessionLineageQueues,
    collapseAllSessionLineageQueues,
    openCurrentSessionLineageQueue,
    sessionQueueAdvanceFeedback,
    sessionQueueAdvanceFocusSummary,
    sessionQueueFocusDelta,
    sessionQueueAdvanceNoticeActions,
    attentionQueuePosition,
    hiddenAttentionQueueCount,
    attentionSessionLineageQueue,
    toggleSessionLineageQueueExpansion,
    restoreSessionLineageQueue,
    sessionLineagePriority,
    sessionLineageTraits,
    snoozeSessionLineageQueueEntry,
    advanceSessionLineageQueueFromEntry,
    dismissSessionLineageQueueEntry,
    findSessionLineageEntryInSession,
    revealSessionLineageEntryInTimeline,
    decisionQueuePosition,
    hiddenDecisionQueueCount,
    decisionSessionLineageQueue,
    visibleSessionLineageEntries,
    triageInboxItemCount,
    triageInboxItems,
    selectedTriageInboxItem,
    syncedTriageInboxItem,
    inspectTriageInboxItem,
    inspectAndAdvanceTriageInboxItem,
    advanceTriageInboxCursor,
    syncTriageInboxCursorToSelection,
    triageInboxFeedbackHistoryCount: triageInboxFeedbackHistory.length,
    triageInboxFeedbackFilter,
    setTriageInboxFeedbackFilter,
    triageInboxFeedbackCounts,
    triageInboxFeedback,
    groupedRecentTriageInboxFeedback,
    recentTriageInboxFeedbackCount: recentTriageInboxFeedback.length,
    expandedTriageInboxResultGroups,
    currentTriageInboxFeedbackGroup,
    expandAllTriageInboxResultGroups,
    collapseAllTriageInboxResultGroups,
    openCurrentTriageInboxResultGroup,
    toggleTriageInboxResultGroup,
    openTriageInboxHistoryGroup,
    snoozeTriageInboxItem,
    dismissTriageInboxItem,
    runtimeAgentSectionProps: buildRuntimeAgentSectionProps({
      selectedAgentId,
      agentLoading,
      selectedAgent,
      busyActionKey,
      formatTimestamp,
      toNumber,
      toStringValue,
      formatJson,
      toNullableNumber,
      asRecord,
      describeRunResult,
      outcomeProjectId,
      outcomeStoryId,
      selectedRunId,
      setSelectedRunId,
      selectedRunResultIndex,
      setSelectedRunResultIndex,
      focusRuntimeAgent,
      runAgentSuggestedCommand,
      agentScopedRuns,
      agentActivitySearch,
      setAgentActivitySearch,
      agentActivityFilter,
      setAgentActivityFilter,
      filteredAgentScopedRuns,
      agentScopedOutcomes,
      filteredAgentScopedOutcomes,
      setEntitySearch,
      activeAgentTimelineEntries,
      hiddenAgentTimelineEntryCount,
      agentTimelineSearch,
      setAgentTimelineSearch,
      agentTimelineFilter: agentTimelineFilter as
        | "all"
        | "approvals"
        | "issues"
        | "events"
        | "attention",
      setAgentTimelineFilter: (value) => {
        setAgentTimelineFilter(value);
      },
      persistedDismissedAgentTimelineCount,
      persistedSnoozedAgentTimelineCount,
      agentTimelinePriorityCounts,
      nextBestAgentTimelineEntry,
      hasPersistedAgentTimelinePreferences,
      inspectAgentTimelineEntry,
      restoreAgentTimelineHidden,
      exportAgentTimelinePreferences,
      resetAgentTimelinePreferences,
      agentQueueAdvanceFeedback,
      agentQueueAdvanceFocusSummary,
      agentQueueFocusDelta,
      agentQueueAdvanceNoticeActions,
      nextCriticalAgentTimelineEntry,
      nextHighAgentTimelineEntry,
      expandedAgentPriorityQueues,
      currentAgentPriorityQueue,
      expandAllAgentPriorityQueues,
      collapseAllAgentPriorityQueues,
      openCurrentAgentPriorityQueue,
      criticalAgentTimelineQueue,
      criticalAgentTimelineTotal: criticalAgentTimelineEntries.length,
      criticalAgentTimelinePosition,
      highAgentTimelineQueue,
      highAgentTimelineTotal: highAgentTimelineEntries.length,
      highAgentTimelinePosition,
      toggleAgentPriorityQueueExpansion,
      filteredAgentTimelineEntriesCount: filteredAgentTimelineEntries.length,
      visibleAgentTimelineEntries,
      selectedAgentTimelineEntry,
      selectedAgentTimelineRunLink,
      selectedAgentTimelinePriority,
      latestAgentIssueEntry,
      latestAgentApprovalEntry,
      latestAgentEventEntry,
      syncLinkedSelection,
      approveApproval,
      rejectApproval,
      applyApproval,
      resolveIssue,
      advanceCurrentAgentPriorityQueue: (entry) => {
        if (currentAgentPriorityQueue) {
          advanceAgentPriorityQueueFromEntry(currentAgentPriorityQueue, entry);
        }
      },
      focusAgentTimeline,
      setEventFilter: (value) => {
        setEventFilter(value);
      },
      snoozeAgentTimelineEntry,
      dismissAgentTimelineEntry,
      advanceAgentPriorityQueueFromEntry,
      findAgentTimelineEntryInSession,
      revealAgentTimelineEntry,
      agentTimelineEntryKey,
      agentTimelinePriority,
      agentTimelineRowDomId,
    }),
    controlSummary,
    recentSessions,
    totalSessionCount: sessions.length,
    selectedSessionId,
    sessionSummary,
  });

  const sessionDrilldownSectionProps = buildSessionDrilldownSectionProps({
    selectedSessionId,
    sessionLoading,
    selectedSession,
    selectedControl,
    linkedAgentIds,
    selectedAgentId,
    focusRuntimeAgent,
    filteredRuns,
    linkedRuns,
    filteredEvents,
    filteredApprovals,
    linkedApprovals,
    visibleSessionApprovals,
    filteredIssues,
    linkedIssues,
    visibleSessionIssues,
    entitySearch,
    setEntitySearch,
    sortedProfiles,
    busyActionKey,
    applyControlPlan,
    applyRecommendation,
    runFilter: runFilter as "all" | "execute" | "preview" | "attention",
    setRunFilter,
    matchesRunFilter,
    selectedRunId,
    setSelectedRunId,
    setSelectedRunResultIndex,
    toNumber,
    eventFilter: eventFilter as "all" | "control" | "actions" | "decisions" | "attention",
    setEventFilter,
    matchesEventFilter,
    visibleSessionEvents,
    selectedSessionEventKey,
    toStringValue,
    toStringArray,
    toNullableNumber,
    formatTimestamp,
    eventFamily,
    sessionEventKey,
    sessionContextRowDomId,
    syncLinkedSelection,
    selectedPass,
    setSelectedSessionId,
    selectedSessionApprovalId,
    selectedSessionIssueId,
    revealSelectedSessionContextRow,
    revealSelectedSessionContextInAgentTimeline,
    selectedSessionContext,
    formatJson,
    asRecord,
    describeRunResult,
    resolveRunLinkFromContext,
    currentSessionLineageQueue,
    selectedSessionLineageEntry,
    advanceSessionLineageQueueFromEntry,
    approveApproval,
    rejectApproval,
    applyApproval,
    resolveIssue,
  });

  const headerSectionProps = buildHeaderSectionProps({
    latestControlPassAt: controlSummary.latest_control_pass_at,
    latestSessionAt: sessionSummary.latest_session_at,
    selectedSessionId,
    selectedControlState: selectedControl?.state || null,
    refreshing,
    refresh,
    formatTimestamp,
    controlSummary,
    sessionSummary,
    historySearch,
    setHistorySearch,
    filteredSessionHistoryCount: filteredSessionHistory.length,
    totalSessionCount: sessions.length,
    filteredControlPassHistoryCount: filteredControlPassHistory.length,
    totalControlPassCount: controlPasses.length,
  });

  const mainSectionsProps = buildMainSectionsProps({
    notice,
    errorMessage,
    workspaceSectionProps,
    sessionDrilldownSectionProps,
  });

  return (
    <ControlPlaneLayout
      health={health}
      visibleProjects={visibleProjects}
      headerSectionProps={headerSectionProps}
      mainSectionsProps={mainSectionsProps}
    />
  );
}
